### ISSUE TITLE
Establish a home for the 'Prioritised Checklist of known issues' 

### ISSUE THREAD

**Issue by reiterative** [elisa-tech/wg-osep#22]
Igor Stoppa proposed the creation of a [prioritised checklist of known issues](https://drive.google.com/file/d/1b37qOOHHixAbD3Cp9QosG3IYoxAQulMW) relating to the use of Linux in safety applications at the 2023-10 Munich ELISA workshop.

Igor has written some 'seed documents' that begin to describe a set of known issues, and has suggested that ELISA host and manage a 'fork' of these documents, to be extended by contributions from ELISA and the wider open source community, and a register of items for the proposed checklist.

**Comment by reiterative** [comment]
I think we can perhaps consider this addressed, as a version of [the checklist](https://github.com/elisa-tech/wg-osep/blob/main/Contributions/CheckList_for_Safety_Claims_on_a_Generic_Linux_System.md) has found a home in the OSEP repository.

**Comment by igor-stoppa** [comment]
Agree, thanks
